# Generated by Django 5.2.5 on 2025-09-10 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administradores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administradores',
            options={'managed': False},
        ),
    ]
