# Generated by Django 5.2.5 on 2025-09-10 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publicaciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('fecha_publicacion', models.DateField(blank=True, null=True)),
                ('autor', models.CharField(blank=True, max_length=255, null=True)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'publicaciones',
                'managed': False,
            },
        ),
    ]
